###############################################################################
#
# Makefile for a script (e.g. Python), project 10
#
# Students:
# Aviv Yaish, ID 011111111, master.of.nand@cs.huji.ac.il
# Lisa Simpson, ID 022222222, lisa@cs.huji.ac.il
#
###############################################################################

all:
	chmod a+x JackAnalyzer.py Tokenizer.py CompilationEngine.py
